config:
  modules:
    http_2xx:
      prober: http
      timeout: 5s
      http:
        valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
        follow_redirects: true
        preferred_ip_protocol: "ip4"
        valid_status_codes:
        - 200
        bearer_token: R79BDN21BPNVAFY927RQP171T4NG7G541KZYYFKBJ1PXFWODCS
