- job_name: external-ec2-job
  scrape_interval: 15s
  static_configs:
    - targets: ['3.134.186.4:9100'] # i will just use public ip for this project.

- job_name: blackbox
  metrics_path: /probe
  params:
    module: [http_2xx]
  static_configs:
    - targets:
        - http://3.134.186.4 # rubric
  relabel_configs:
  - source_labels: [__address__]
    target_label: __param_target
  - source_labels: [__param_target]
    target_label: instance
  - target_label: __address__
    replacement: prometheus-blackbox-exporter.monitoring:9115
